### ISSUE TITLE
Auto-fill object id after insert

### ISSUE THREAD

**Issue by marcosmko** [pinchbv/floor#380]
Hello all!

When I insert an object into the database, I can get a int value as the id of my object.
Is there a way to auto-fill the respective object variable?

Without this, I would need to create some boilerplate code just to update the id of my object.

I'm cracking my head so I can better separate modules and integrations with the rest of code, keeping particularities from databases above the DAOs layer.

Example:

```dart
@Entity()
class MyObject {
  MyObject({this.id, this.name});

  @PrimaryKey(autoGenerate: true)
  int id;

  String name;
}
```

```dart
@dao
abstract class MyObjectDAO {
  @Insert()
  Future<void> create(MyObject object);
}
```

This is normally what floor generates:
```dart
class _$MyObjectDAO extends MyObjectDAO {
  [...]

  @override
  Future<void> create(MyObject object) async {
    await _myObjectInsertionAdapter.insert(object, OnConflictStrategy.abort);
  }
}
```

And this is what I would like to achieve:
```dart
class _$MyObjectDAO extends MyObjectDAO {
  [...]

  @override
  Future<void> create(MyObject object) async {
    object.id = await _myObjectInsertionAdapter.insertAndReturnId(object, OnConflictStrategy.abort);
  }
}
```

Of course, there are somethings that I need to assume:
- primary key is int
- primary key is auto generated
- primary key is non final

Does it make sense?

**Comment by mqus** [comment]
We currently don't support this. I'm not sure of the implications (e.g. we currently do not use setters at all) but I think this is worth looking into.

On the other hand, the amount of boilerplate you'll have to write is really limited since you'll only have to write a wrapper for the insert function. If you have multiple entities this can be solved through inheritance of DAOs and entities.

**Comment by mqus** [comment]
e.g. 
```dart
@dao
abstract class MyObjectDAO {
  @Insert()
  Future<int> create(MyObject object);


  Future<void> createWithId(MyObject object) async {
    object.id = await create(object);
  }
}
```

**Comment by marcosmko** [comment]
> e.g.
> 
> ```dart
> @dao
> abstract class MyObjectDAO {
>   @Insert()
>   Future<int> create(MyObject object);
> 
> 
>   Future<void> createWithId(MyObject object) async {
>     object.id = await create(object);
>   }
> }
> ```

This is exactly what I was looking for!
Thank you very much!

**Comment by SEGVeenstra** [comment]
Closing as answered.
If there is a feature request in here, please open it as a new issue.
