### ISSUE TITLE
Add fields to the table

### ISSUE THREAD

**Issue by islinjj** [pinchbv/floor#429]
I want to add fields to the table. I use the database migration method, but the previous data will be lost every time the project restarts. If someone else runs the project for the first time, it means that he is creating the database for the first time , Then running this migration is an error, then how should I add fields to the table is better
```
final migration1to2 = Migration(1, 2, (database) async {
  await database.execute('ALTER TABLE log ADD COLUMN dateTime TEXT');
});

final database = await $FloorAppDatabase
    .databaseBuilder('app_database.db')
    .addMigrations([migration1to2])
    .build();
```

**Comment by vitusortner** [comment]
Hi! Can you show me your database class? It's the one annotated with `@Database`.

**Comment by islinjj** [comment]
> Hi! Can you show me your database class? It's the one annotated with `@Database`.

```
@Database(version: 2, entities: <Type>[Entity])
abstract class AppDatabase extends FloorDatabase {
  Dao get dao;
}
```

**Comment by cassioseffrin** [comment]
@islinjj  may you have your file already in version 2 (for some preview migration, once it's made the number never back), in this case you could try to change it to version:3 and try again.

**Comment by SEGVeenstra** [comment]
Closing due to no response/inactivity
