### ISSUE TITLE
Dart 2.13.4 is incompatible with your dependencies' SDK constraints. Please run "pub get" again.

### ISSUE THREAD

**Issue by HasibPrince** [pinchbv/floor#626]
When we run the code generator command, this error occurs. Adding the pubspec.yaml.

`name: libshared
description: A new Flutter package.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.4
  floor: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  floor_generator: ^1.2.0
  build_runner: `^2.1.4`

**Comment by MrCsabaToth** [comment]
What does your `flutter doctor -v` say?

**Comment by SEGVeenstra** [comment]
Closed due to inactivity
