### ISSUE TITLE
No ForeignKeyAction exists for the onUpdate trigger

### ISSUE THREAD

**Issue by proninyaroslav** [pinchbv/floor#649]
I run:
`flutter pub run build_runner build --delete-conflicting-outputs`

and I get it with the latest Flutter, `analyzer` and `build_runner`:
`No ForeignKeyAction with the value ForeignKeyAction (_name = String ('noAction'); index = int (0)) exists for the onUpdate trigger.`

```Dart
@TypeConverters([TrackingServiceTypeConverter])
@Entity(
  primaryKeys: ['key', 'serviceType'],
  foreignKeys: [
    ForeignKey(
      entity: TrackingServiceInfo,
      childColumns: ['serviceType'],
      parentColumns: ['type'],
      onDelete: ForeignKeyAction.cascade,
    ),
  ],
)
class AuthDataField {
  final String key;

  final String value;

  final TrackingServiceType serviceType;

  const AuthDataField({
    required this.key,
    required this.value,
    required this.serviceType,
  });
}
```

**Comment by proninyaroslav** [comment]
@vitusortner 
I tested on the `develop` branch and the error is the same.

**Comment by dkaera** [comment]
Does this issue occur with the latest version of `Floor`? I tried to reproduce it with the [libertrack](https://github.com/proninyaroslav/libretrack) project, it works fine.

**Comment by proninyaroslav** [comment]
@dkaera 
I couldn't upgrade to new versions of `analyzer` and `build_runner` because of this.

**Comment by dkaera** [comment]
> @dkaera I couldn't upgrade to new versions of `analyzer` and `build_runner` because of this. Maybe this is fixed, it will be clear after the update of dependencies

ok, no problem
FYI: tried to run the code generation without the override `analyzer` in your project, all works fine for me, so probably it's time to migrate to the latest version 😁
