### ISSUE TITLE
You are trying to change an object which is not an entity

### ISSUE THREAD

**Issue by claudneysessa** [pinchbv/floor#651]
I'm migrating a very old app from version 1.20.3 to the newest one that already supports Null Safety, but I'm having a problem with DAO when trying to use notations like @insert it shows an error

 @insert
  Future<void> insertPerson(Person person);

Error: You are trying to change an object which is not an entity

If I go back to the current version and go back to the source, it goes back to normal

**Comment by claudneysessa** [comment]
I identified the same problem when running the GitHub example inside the package repository

**Comment by neeluagrawal04** [comment]
use like this
  @Insert(onConflict: OnConflictStrategy.replace)
  Future<void> insertItem(T item);

**Comment by shindje** [comment]
fixed by adding entity class to AppDatabase (i added wrong entity class before)

**Comment by dkaera** [comment]
Looks like resolved.
