### ISSUE TITLE
UPDATE a BLOB field in an existing SQLite record，floor change it to String

### ISSUE THREAD

**Issue by HXiaoMing** [pinchbv/floor#652]
the entity is:
@Entity(tableName: 'Task')
class Task {
   final Uint8List ext;
   Task(this.ext);
}

the dao is :
@dao
abstract class TaskDao {
 @Query('update Task set ext = :ext')
  Future<void> updateTaskExt(Uint8List ext);
}

i want to update column ext,  ext type is Uint8List，database type is blob，after execute TaskDao method updateTaskExt，ext value change to String！！！

**Comment by dkaera** [comment]
Please double it check. For me, following configuration works fine:

`@Database(version: 1, entities: [Task])
abstract class FlutterDatabase extends FloorDatabase {
  TaskDao get taskDao;
}

@dao
abstract class TaskDao {

  @Query('UPDATE Task set ext = :ext')
  Future<void> updateTaskExt(Uint8List ext);
}

@entity
class Task {
  @PrimaryKey(autoGenerate: true)
  final int? id;

  final String message;

  final Uint8List ext;

  Task(this.id, this.message, this.ext);

}`

generates next code:

`class _$TaskDao extends TaskDao {
  _$TaskDao(this.database, this.changeListener)
      : _queryAdapter = QueryAdapter(database);

  final sqflite.DatabaseExecutor database;

  final StreamController<String> changeListener;

  final QueryAdapter _queryAdapter;

  @override
  Future<void> updateTaskExt(Uint8List ext) async {
    await _queryAdapter
        .queryNoReturn('UPDATE Task set ext = ?1', arguments: [ext]);
  }
}`

**Comment by dkaera** [comment]
Close due to lack of answer from the creator of the question. Looks like the question might be solved by the suggestion in the comment.

**Comment by HXiaoMing** [comment]
> Please double it check. For me, following configuration works fine:
> 
> ```
> @Database(version: 1, entities: [Task])
> abstract class FlutterDatabase extends FloorDatabase {
>   TaskDao get taskDao;
> }
> 
> @dao
> abstract class TaskDao {
> 
>   @Query('UPDATE Task set ext = :ext')
>   Future<void> updateTaskExt(Uint8List ext);
> }
> 
> @entity
> class Task {
>   @PrimaryKey(autoGenerate: true)
>   final int? id;
> 
>   final String message;
> 
>   final Uint8List ext;
> 
>   Task(this.id, this.message, this.ext);
> 
> }
> ```
> 
> generates next code:
> 
> ```
> class _$TaskDao extends TaskDao {
>   _$TaskDao(this.database, this.changeListener)
>       : _queryAdapter = QueryAdapter(database);
> 
>   final sqflite.DatabaseExecutor database;
> 
>   final StreamController<String> changeListener;
> 
>   final QueryAdapter _queryAdapter;
> 
>   @override
>   Future<void> updateTaskExt(Uint8List ext) async {
>     await _queryAdapter
>         .queryNoReturn('UPDATE Task set ext = ?1', arguments: [ext]);
>   }
> }
> ```

after updateTaskExt，try to read it， then will throw error.

**Comment by dkaera** [comment]
Hey @HXiaoMing 
I did some investigation and `sflite` has the same problem. Honestly, using `query` to update the data is not the right way to go, but it is possible in some extreme cases as a workaround. For this particular case I would recommend you use `rawUpdate`. Sample of the code you can see in my [PR](https://github.com/HXiaoMing/floor_new_issue/pull/2/files) to your repository.

PS: this issue brings me an idea that `DatabaseExecutor` should be accessible in DAO classes to use `raw` methods without global variables.

**Comment by SEGVeenstra** [comment]
Closing: Inactive
