### ISSUE TITLE
Query parameter for generic is not supported from 1.2.0

### ISSUE THREAD

**Issue by wangmir** [pinchbv/floor#661]
I'm using BaseDao something like this.

```dart
abstract class BaseDao<T> {
  @Insert(onConflict: OnConflictStrategy.replace)
  Future<void> insert(T obj);

  @Insert(onConflict: OnConflictStrategy.replace)
  Future<void> inserts(List<T> objs);

  @Update(onConflict: OnConflictStrategy.replace)
  Future<void> update(T obj);

  @delete
  Future<void> remove(T obj);

  @Query("SELECT * FROM \$dbTable WHERE id = :id")
  Future<T?> findById(int id);

  @Query("SELECT * FROM \$dbTable")
  Future<List<T>> findAll();
}

```

And this `BaseDao` is used by actual implementation like, 

```dart
@dao
abstract class BuildingDao extends BaseDao<BuildingEntity> {
  final dbTable = "BuildingEntity";

  @Query("SELECT * FROM \$dbTable WHERE slug = :slug")
  Future<BuildingEntity?> getBuilding(String slug);
}
```
And, the generated code for this was something like 

```dart

  @override
  Future<BuildingEntity?> getBuilding(String slug) async {
    return _queryAdapter.query('SELECT * FROM $dbTable WHERE slug = ?1',
        mapper: (Map<String, Object?> row) => BuildingEntity(
            row['id'] as int,
            row['slug'] as String,
            row['storeId'] as String?,
            row['name'] as String,
            row['desc'] as String),
        arguments: [slug]);
  }

  @override
  Future<BuildingEntity?> findById(int id) async {
    return _queryAdapter.query('SELECT * FROM $dbTable WHERE id = ?1',
        mapper: (Map<String, Object?> row) => BuildingEntity(
            row['id'] as int,
            row['slug'] as String,
            row['storeId'] as String?,
            row['name'] as String,
            row['desc'] as String),
        arguments: [id]);
  }
```

But from 1.2.0, `\$dbTable` is not available for query... the generated query didn't remove slash from that so g file was like,

```dart
  @override
  Future<BuildingEntity?> getBuilding(String slug) async {
    return _queryAdapter.query('SELECT * FROM \$dbTable WHERE slug = ?1',
        mapper: (Map<String, Object?> row) => BuildingEntity(
            row['id'] as int,
            row['slug'] as String,
            row['storeId'] as String?,
            row['name'] as String,
            row['desc'] as String),
        arguments: [slug]);
  }

  @override
  Future<BuildingEntity?> findById(int id) async {
    return _queryAdapter.query('SELECT * FROM \$dbTable WHERE id = ?1',
        mapper: (Map<String, Object?> row) => BuildingEntity(
            row['id'] as int,
            row['slug'] as String,
            row['storeId'] as String?,
            row['name'] as String,
            row['desc'] as String),
        arguments: [id]);
  }
```

So it causes sqliteException.

How can i solve this problem from 1.2.0?

**Comment by dkaera** [comment]
Honestly, this looks like a bug in the `code_builder` package, which has been fixed in recent versions.
Basically in Android Room integration, using variable table name in DAO is solved by using RawQuery integration in BaseDao. 
I want to implement this soon, so I would suggest a workaround for you now.
- fork the project repo
- replace the line 160 in floor_generator/lib/writer/query_method_writer.dart by the next code:

`return code.toString().replaceAll(r'\$', r'$');`

**Comment by ebelevics** [comment]
One good solution would be, if child class @Dao annotation would have parameter "tableName" where value is replacing specific abstract string (for example $dbTable or whatever else in @Query('SELECT * FROM \$dbTable WHERE id = ?1)') in base Dao class.
Therefore generic queries like findById could be abstracted.

**Comment by dkaera** [comment]
@ebelevics The main problem here is that we cannot use any variables in the annotations, they can only be constant.

**Comment by dkaera** [comment]
@ebelevics yes, I understand your idea, but if we take a look at Android Room integration they provide this option only by RawQuery. The main idea of this project is to make it easy for an Android developer knowing Room to switch to Flutter.

I think the RawQuery integration should solve a lot of issues in one go.

**Comment by dkaera** [comment]
solved

**Comment by alimcomp** [comment]
Hi,
It's not resolved and the problem exists
