### ISSUE TITLE
Missing homepage

### ISSUE THREAD

**Issue by kwameopareasiedu** [pinchbv/floor#673]
I noticed that the neither of the project websites [https://floor.codes](https://floor.codes) and [https://vitusortner.github.io/floor/](https://vitusortner.github.io/floor/) is available.

Could we please have an alternative since the full documentation exists there?

**Comment by ThomasMiddel** [comment]
Hi @kwameopareasiedu, I will make sure to update the links today. For now, you can find the documentation here: https://pinchbv.github.io/floor/
