### ISSUE TITLE
query LIKE keywork

### ISSUE THREAD

**Issue by vohoangtuit** [pinchbv/floor#679]
I want to query tableName WHERE keywork LIKE :keywork, not working

**Comment by dkaera** [comment]
Please add your sample of code.
Basically, to create a query method you need to add next code

```
@Query('SELECT * FROM task WHERE id = :id')
  Future<Task?> findTaskById(int id);
```

For more information please take a look [floor samples](https://github.com/pinchbv/floor/tree/develop/example/lib) or [documentation](https://pinchbv.github.io/floor/daos/)

**Comment by vohoangtuit** [comment]
This is My code:

@Query('SELECT * FROM KeyWorkDBModel WHERE keyword =  :keyWork')
  Future<KeyWorkDBModel?> getKeyWorkBYID(String keyWork);

**Comment by dkaera** [comment]
@vohoangtuit  `@query` should start with a capital letter `@Query`. 
Need to take a look on `KeyWorkDBModel` code. It should include `@entity` and `@@primaryKey` (or `@PrimaryKey(autoGenerate: true)`) declaration

**Comment by vohoangtuit** [comment]
i find solution : https://github.com/pinchbv/floor/issues/154

thanks
