### ISSUE TITLE
Database Backup

### ISSUE THREAD

**Issue by balenaultra** [pinchbv/floor#680]
There is any way to make a full backup of a database?

I facing some problems on my app that is only occurring on  some user devices there was miles away from me.

There is some data error on the database and i can't reproduce in my devices.

So I think if I can get his database and use it om my device i can have a better chance do solve this problem.

**Comment by dkaera** [comment]
I don't think it should be part of the ORM framework,
but in any case you can use the general approach to get the database file and add it as an assert.

To get the .db file you need to 
- add a method to the inherited abstract class `FloorDatabase` to get the path to .db file:
```
@Database(version: [<your_db_version>], entities: [<your_table_models>])
abstract class FlutterDatabase extends FloorDatabase {
  
  //......
  // Here your DAO getters
  //......

  Future<String> getDatabasesPath() {
    return sqfliteDatabaseFactory.getDatabasesPath();
  }
}
```
- add logic to exchange database snapshots (you can get the .db file from the above path).
- implement the logic to add the database from assert, `sqflite` provides good [instructions for that](https://github.com/tekartik/sqflite/blob/master/sqflite/doc/opening_asset_db.md)

**Comment by iibalena** [comment]
Thanks, it solved my problem.

**Comment by dkaera** [comment]
Looks like solved, so I close it.

**Comment by ChristianNavolskyi** [comment]
Would it be possible to have that method `getDatabasePath()` in `FloorDatabase`?

That way the user could override the database location to use
In my case, I would like to have the db file reside in the app specific folder on iOS (hidden from the user) and not in the document folder in the Files app.
