### ISSUE TITLE
SqfliteDatabaseException

### ISSUE THREAD

**Issue by LiXiaoQiang4514** [pinchbv/floor#682]
DatabaseException(Row too big to fit into CursorWindow requiredPos=27, totalRows=28) sql 'SELECT * FROM chats' args []

**Comment by dkaera** [comment]
> DatabaseException(Row too big to fit into CursorWindow requiredPos=27, totalRows=28) sql 'SELECT * FROM chats' args []

This is a common problem when you try to save large images to the database. If this is the problem, it is better to save the image to the phone storage and only save the path to the file in the database.

**Comment by dkaera** [comment]
closed as answered
