### ISSUE TITLE
Is it possible to return object(int, List<int>...) after executing query

### ISSUE THREAD

**Issue by vovaklh** [pinchbv/floor#687]
I want to get a list of Ids after executing query. Is it possible?

**Comment by dkaera** [comment]
Yes, it's possible with [database-views](https://pinchbv.github.io/floor/database-views/)
Here is a [sample](https://github.com/pinchbv/floor/compare/develop...dkaera:floor:feature/database_view_sample) for fetching messages from the `task` table. You can follow this approach to get a list of `Ids`.

**Comment by dkaera** [comment]
Close as a duplicate of #528
