### ISSUE TITLE
’delete from table where id in (:ids)‘ statement supported?

### ISSUE THREAD

**Issue by nomisshe** [pinchbv/floor#698]
@Query('delete from table where id in (:ids)')
  Future<void> deleteInfoForIds(String ids);

after build  error
The parameter ids should be referenced without `IN` Change the type of ids to be a List<> orreference it without `IN`, e.g. `IS :ids`.

**Comment by dkaera** [comment]
That's correct
First, if you use `IN` in `query`, the argument should be `list`.
Second, don't forget to specify a return type.
So in your case, a query request should look like:

```dart
@Query('delete from table where id in (:ids)')
Future<void> deleteInfoForIds(List<String> ids);
```

**Comment by nomisshe** [comment]
nice，thankyou

**Comment by dkaera** [comment]
> nice，thankyou and I hope you can write more methods about common sqlite statements in the examples，thanks

sure, no problem
We try to make the project documentation simple and easy to read. For more code samples, I would suggest looking at the project tests, which cover many different use cases.

**Comment by aa2013** [comment]
> That's correct First, if you use `IN` in `query`, the argument should be `list`. Second, don't forget to specify a return type. So in your case, a query request should look like:
> 
> ```dart
> @Query('delete from table where id in (:ids)')
> Future<void> deleteInfoForIds(List<String> ids);
> ```


Why can't I? prompt
`The parameter tags should be referenced like a list (`x IN (:tags)`) Change the type of tags to not be a List<> orreference it with ` IN (:tags)` (including the parentheses).
`
```
  @Query("""
  select his.* from (
    select * from History
    where uid = :uid
       and id > :fromId
       and case when :content = ''
             then 
               1
             else 
               content like '%'||:content||'%'
           end
       and case when :type = ''
             then 
               1
             else 
               type = :type
           end
       and case when :startTime = '' or :endTime = ''
             then 
               1
             else 
               date(time) between :startTime and :endTime
           end
  ) his
  where 
    case when :tags = '' then
      1
    else
      his.id in (
        select distinct hisId 
        from HistoryTag ht 
        where tagName in (:tags)
      )
    end
  order by top desc,id desc
  """)
  Future<List<History>> getHistoriesPageByWhere(
    int uid,
    int fromId,
    String content,
    String type,
    List<String> tags,
    String startTime,
    String endTime,
  );
```
