### ISSUE TITLE
Support Analyzer 5

### ISSUE THREAD

**Issue by MrCsabaToth** [pinchbv/floor#700]
On the path of #659, #667, #594, now analyzer is at v5.x, but floor_generator depends on v4.x.

**Comment by dkaera** [comment]
> On the path of #659, #667, #594, now analyzer is at v5.x, but floor_generator depends on v4.x.

After a long break, I want to present MR #705  with the transition to analyzer 5 and all the latest updates

**Comment by cogivn** [comment]
Hi, 
I am also facing this issue. Can I ask when this problem will be fixed?
Thanks,

**Comment by dkaera** [comment]
> Hi, I am also facing this issue. Can I ask when this problem will be fixed? Thanks,

Pinchbv is busy with the current deadlines. Pull request is ready for review.
So we're waiting for updates.

**Comment by dkaera** [comment]
@MrCsabaToth @cogivn 
it's done, I think we can close this issue.

**Comment by MrCsabaToth** [comment]
Release 1.4.0 https://github.com/pinchbv/floor/commit/c6b561c44b99d2d3438ad59858910012f0ca95cf and 1.4.1 https://github.com/pinchbv/floor/commit/ae4b2c85fc14f2f40bbabf5979d0148cd5008b9e fixed this issue
