### ISSUE TITLE
It needs overall  update

### ISSUE THREAD

**Issue by Mahm0ud-Ahmed** [pinchbv/floor#703]

**Comment by dkaera** [comment]
@Mahm0ud-Ahmed please add details.

**Comment by Mahm0ud-Ahmed** [comment]
> @Mahm0ud-Ahmed please add details.

The most important is that it needs to be integrated with analyzer 5.

**Comment by dkaera** [comment]
> > @Mahm0ud-Ahmed please add details.
> 
> The most important is that it needs to be integrated with analyzer 5.

ok, we'll  focus on that next

**Comment by dkaera** [comment]
close as a duplicate of #700
