### ISSUE TITLE
table name is dynamic alert error

### ISSUE THREAD

**Issue by nomisshe** [pinchbv/floor#704]
i want dynamic change table name 
for example 
 @Query('select * from bk_info_:id order by num asc')
  Future<List<InfoBean>> findAllbkInfos(String id);

but alert error 
DB Error: 1 "near "?": syntax error"
DB Query: select * from bk_info_?1 order by num asc
What do I need to do？

**Comment by dkaera** [comment]
> i want dynamic change table name for example @query('select * from bk_info_:id order by num asc') Future<List> findAllbkInfos(String id);
> 
> but alert error DB Error: 1 "near "?": syntax error" DB Query: select * from bk_info_?1 order by num asc What do I need to do？

I think you need to add a space between `bk_info_` and `:id`, if the table name is `bk_info_`

**Comment by nomisshe** [comment]
> 
@query('select * from bk_info_:id order by num asc')
Future<List> findAllbkInfos(String id);
if id = '123'
i hope table name is bk_info_123

**Comment by dkaera** [comment]
> > 
> @query('select * from bk_info_:id order by num asc') Future findAllbkInfos(String id); if id = '123' i hope table name is bk_info_123

No, `floor` does not support dynamic table names, as an option, you can use a raw query.
