### ISSUE TITLE
pub.dev Page for this Package Wrong Link

### ISSUE THREAD

**Issue by acuba001** [pinchbv/floor#706]
As of right now, the link for the documentation for this Flutter package on pub.dev currently leads to "floor.codes". I noticed that the `README.md` for this repo has an updated link that seems to go to the correct site (https://pinchbv.github.io/floor/). 

<img width="966" alt="Screenshot 2022-11-19 at 5 47 39 PM" src="https://user-images.githubusercontent.com/4492431/202874517-903d02c5-1e5d-47c9-b648-d1e958b3771a.png">

**Comment by dkaera** [comment]
Good point @acuba001 Will fix that in the next release. Thanks

**Comment by dkaera** [comment]
PR #714  has been created.
