### ISSUE TITLE
There is no migration to upgrade the database to the current version. Abort migration.

### ISSUE THREAD

**Issue by Soliardi-Chyngyz** [pinchbv/floor#707]
Please give an answer, I have already used your package in the project, many people have downloaded it and I cannot suggest them to delete the project and download it again. Please give detailed information on migration! Thanks

**Comment by dkaera** [comment]
To get more information about the migration process please use [doc](https://pinchbv.github.io/floor/migrations/)

**Comment by dkaera** [comment]
closed as answered in discussions #592
