### ISSUE TITLE
Invalid argument(s) Failed to load dynamic library sqlite3.dll error code 126

### ISSUE THREAD

**Issue by todoline-plus-plus** [pinchbv/floor#708]
I run my code as debug mode, all fine.

Then, I use following command to build exe file : 
~~~cmd
flutter build windows
~~~
After that, I double-click the exe file, I found that it's blocking at first page, there's no data shown.

I don't know what to do next, I cannot debug the code.

So, I try to use local_notifier to show the error code.
Following is error message :
~~~txt
Invalid argument(s) Failed to load dynamic library sqlite3.dll error code 126
~~~

Error occurred when "open"  method called which define in xxx.g.dart, following is the code:
~~~dart
Future<TodoLineDatabase> build() async {
    final path = name != null
        ? await sqfliteDatabaseFactory.getDatabasePath(name!)
        : ':memory:';
    final database = _$TodoLineDatabase();
    database.database = await database.open(
      path,
      _migrations,
      _callback,
    );
    return database;
  }
~~~
**"database.open" throwing the exception**.

Why debug mode is fine when running exe file throw the exception?
I think there must be argument(s) need to pass to database.open method, but it didn't.

I have notice the issue:
[issue 615](https://github.com/pinchbv/floor/issues/615)

It say that permission cause the error, I have change my code, bellow is the code which has changed:
~~~dart
Future<TodoLineDatabase> build() async { 
  final p = await PathProviderWindows().getApplicationDocumentsPath(); 
  final path = name != null ? p! + '/' + name! : ':memory:'; 
  final database = _$TodoLineDatabase();
  database.database = await database.open( path, _migrations, _callback, ); 
  return database; 
} 
~~~

But it didn't worked.

**Comment by todoline-plus-plus** [comment]
Here is flutter doctor outputs:
~~~cmd
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.3.5, on Active code page: 65001

Microsoft Windows [Version 10.0.17134.1304], locale zh-CN)                                                                                                                             C
hecking Android licenses is taking an unexpectedly long time...[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.4.1)
[√] Android Studio (version 2020.3)
[√] Connected device (2 available)
[√] HTTP Host Availability

• No issues found!
~~~

**Comment by todoline-plus-plus** [comment]
I have fixed this issue,  see more from [here](https://stackoverflow.com/questions/66841982/flutter-desktop-sqflite-ffi-throwing-error-on-release-mode):
Just put a sqlite3.dll in the same folder with exe file.

**Comment by aa2013** [comment]
> I have fixed this issue, see more from [here](https://stackoverflow.com/questions/66841982/flutter-desktop-sqflite-ffi-throwing-error-on-release-mode): Just put a sqlite3.dll in the same folder with exe file.

Thank you, it's resolved
