### ISSUE TITLE
floor can support son model?

### ISSUE THREAD

**Issue by zeqinjie** [pinchbv/floor#715]
db can support son model?
```
@entity
class Task {
  @PrimaryKey(autoGenerate: true)
  final int? id;

  final String message;

  final Detail detail;
   ...
}

@entity
class Detail {
   final String message;
   ...
}
```

**Comment by dkaera** [comment]
yep, to solve it quickly you can use [type converters ](https://pinchbv.github.io/floor/database-views/) or you need to set up [table relationships](https://pinchbv.github.io/floor/entities/#primary-keys).

**Comment by zeqinjie** [comment]
> yep, to solve it quickly you can use [type converters ](https://pinchbv.github.io/floor/database-views/) or you need to set up [table relationships](https://pinchbv.github.io/floor/entities/#primary-keys).

thx, can i return type when i delete data，now generate was `queryNoReturn `, return type was  `Future<void>`
```
 @Query(
      'DELETE FROM ListChatModel WHERE uid in (:uids) AND selfImUId = :selfImUId')
  Future<int> deleteModelByUIds(
    List<String> uids,
    String selfImUId,
  );

  // generate code was  queryNoReturn
  @override
  Future<void> deleteModelByUIds(
    List<String> uids,
    String selfImUId,
  ) async {
    const offset = 2;
    final _sqliteVariablesForUids =
        Iterable<String>.generate(uids.length, (i) => '?${i + offset}')
            .join(',');
    await _queryAdapter.queryNoReturn(
        'DELETE FROM ListChatModel WHERE uid in (' +
            _sqliteVariablesForUids +
            ') AND selfImUId = ?1',
        arguments: [selfImUId, ...uids]);
  }
```

**Comment by dkaera** [comment]
I believe you receive an error when running generation. Because for a single return Future it must be nullable.
so in your case, for one record it should be 
`Future<**int?**> deleteModelByUId`
Note that the delete operation returns the row ID if successful and -1 if not, according to the SQLite doc.

P.S.: for the list result it will be:
`Future<**List<int>**> deleteModelByUId`

**Comment by zeqinjie** [comment]
> I believe you receive an error when running generation. Because for a single return Future it must be nullable. so in your case, for one record it should be `Future<int?> deleteModelByUId` Note that the delete operation returns the row ID if successful and -1 if not, according to the SQLite doc.
> 
> P.S.: for the list result it will be: `Future<List<int>> deleteModelByUIds`

@dkaera  thx, i can generate success, but `_queryAdapter.queryNoReturn` was return Future<void> . see the screenshot
```
Future<void> queryNoReturn(
    final String sql, {
    final List<Object>? arguments,
  }) async {
    // TODO #94 differentiate between different query kinds (select, update, delete, insert)
    //  this enables to notify the observers
    //  also requires extracting the table name :(
    await _database.rawQuery(sql, arguments);
  }
```
<img width="1294" alt="image" src="https://user-images.githubusercontent.com/8444646/207244349-b6c5360f-7797-40a8-a776-69173ddeee5f.png">

**Comment by dkaera** [comment]
that's odd 🤔
@zeqinjie can you share your DAO for `DetailsChatItemModel` please
Is this method declared as shown below?

```dart
@Query('DELETE FROM DetailsChatItemModel WHERE selfImUId = :selfImUId')
Future<int?> deleteModelBySelfImUId(String selfImUId)
```

**Comment by zeqinjie** [comment]
@dkaera example code
```
// DAO
 @Query(
      'DELETE FROM ListChatModel WHERE uid in (:uids) AND selfImUId = :selfImUId')
  Future<int?> deleteModelByUIds(
    List<String> uids,
    String selfImUId,
  );

// generate code
@override
  Future<int?> deleteModelByUIds(
    List<String> uids,
    String selfImUId,
  ) async {
    const offset = 2;
    final _sqliteVariablesForUids =
        Iterable<String>.generate(uids.length, (i) => '?${i + offset}')
            .join(',');
    await _queryAdapter.queryNoReturn(
        'DELETE FROM ListChatModel WHERE uid in (' +
            _sqliteVariablesForUids +
            ') AND selfImUId = ?1',
        arguments: [selfImUId, ...uids]);
  }

```

**Comment by dkaera** [comment]
@zeqinjie 
sorry to be ahead of the curve. The current version of Floor does not support primitive Dart types for queries. I hope this will be published very soon #691

**Comment by zeqinjie** [comment]
> @zeqinjie sorry to be ahead of the curve. The current version of Floor does not support primitive Dart types for queries. I hope this will be published very soon #691

Thanks for the answer

**Comment by dkaera** [comment]
@zeqinjie feature has been released, welcome to check :)

**Comment by zeqinjie** [comment]
> @zeqinjie feature has been released, welcome to check :)

OK thx
