### ISSUE TITLE
Insert entire list without duplication & UNIQUE constraint failed

### ISSUE THREAD

**Issue by RzTutul** [pinchbv/floor#716]
**Here I want to insert some static categories when the app will be lunch. the first time it was inserted successfully but the second when the app lunch it show "UNIQUE constraint failed". I want if categories name already exists then it should be ignored **
here is my code : 

@Database(version: 1, entities: [CategoriesEntity])
abstract class AppDatabase extends FloorDatabase {
  HishabDao get hishabDao;
}

**Entity**
@Entity(tableName : "cate_tbl",indices : [Index(value : ["cata_name"], unique : true)])
class CategoriesEntity {
  @PrimaryKey(autoGenerate: true)
  final int? id;
  final String cata_name;
  CategoriesEntity(this.id,this.cata_name);
}

**DAO**
  @Insert(onConflict : OnConflictStrategy.ignore)
  Future<void> insertCategories(List<CategoriesEntity> cate);

**List**
 static final List<CategoriesEntity> listCate = [
     CategoriesEntity(null,"Short"),
     CategoriesEntity(null, "Medium"),
     CategoriesEntity(null,"Large"),
   ];

void main() async{
  WidgetsFlutterBinding.ensureInitialized();
  final database = await $FloorAppDatabase.databaseBuilder('app_database.db').build();
  final hishabDao = database.hishabDao;
  await hishabDao.insertCategories(HelperUtils.listCate);
  runApp(const MyApp());
}

**ERROR**

E/flutter (10713): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: DatabaseException(UNIQUE constraint failed: cate_tbl.cata_name (code 2067 SQLITE_CONSTRAINT_UNIQUE)) sql 'INSERT OR ABORT INTO cate_tbl (id, cata_name) VALUES (NULL, ?)' args [Small]

**Comment by dkaera** [comment]
@RzTutul 
hmm, I think you need to set ids into your `listCate`
```dart
static final List listCate = [
CategoriesEntity(1,"Short"),
CategoriesEntity(2, "Medium"),
CategoriesEntity(3,"Large"),
];
```
I don't know why you are getting this error above, it needs to be investigated a bit.
but the option above should help solve the problem.

**Comment by RzTutul** [comment]
@dkaera  But I set the id as the primary key with auto-increment 
btw, if I provide id the occurred same error second time when the app lunch.

**Comment by dkaera** [comment]
@RzTutul just checked your integration
it works fine for me with ID autoincrement, please see stored DB records below:
![image](https://user-images.githubusercontent.com/3041697/207960159-cf063972-23b1-4800-a841-b9caad54397e.png)
no errors in the logs, even after adding new values or restarting the application. Please check the generated code for creating the table structure, it should be like this:

```dart
        await database.execute(
            'CREATE TABLE IF NOT EXISTS `cate_tbl` (`id` INTEGER PRIMARY KEY AUTOINCREMENT, `cata_name` TEXT NOT NULL)');
        await database.execute(
            'CREATE UNIQUE INDEX `index_cate_tbl_cata_name` ON `cate_tbl` (`cata_name`)');
```

**Comment by dkaera** [comment]
there are no updates here, so it looks like the problem is solved
