### ISSUE TITLE
[Question] Paging with Floor database

### ISSUE THREAD

**Issue by cogivn** [pinchbv/floor#719]
Hi,

i try to implement load pagination with floor database but i can't find any documentation mentioning this.
Do we have any way like android `Paging Library 3` or any solution to implement this?
Here is my database code:

```dart
@entity
class Fruit {
  @primaryKey final int id;
  final String name;

  const Fruit(this.id, this.name);
}
```

```dart
@dao
abstract class FruitDao{

  @Query('SELECT * FROM Fruit')
  Future<List<Fruit>> findAllFruits();
}
```

thank you so much,

**Comment by dkaera** [comment]
Hi @cogivn 
no, Floor only provides an abstraction layer over SQLite. The SQLite documentation has a chapter explains how to implement a [sliding window](https://www2.sqlite.org/cvstrac/wiki?p=ScrollingCursor)
