### ISSUE TITLE
ImmutableBuffer error in creating mocks with AssetBundle

### ISSUE THREAD

**Issue by BetterB0y** [pinchbv/floor#725]
With version: 1.3.0
Mock is generating correctly:
```
 @override
  _i19.Future<_i23.ImmutableBuffer> loadBuffer(String? key) =>
      (super.noSuchMethod(
        Invocation.method(
```
where _i23 is "dart:ui"

With version: 1.4.1
Mock is created with error. There is no import: "dart:ui"
```
test/mock.mocks.dart:3473:24: Error: The return type of the method 'MockAssetBundle.loadBuffer' is 'Future<dynamic>', which does not match the return type, 'Future<ImmutableBuffer>', of the overridden method, 'AssetBundle.loadBuffer'.
 - 'Future' is from 'dart:async'.
 - 'ImmutableBuffer' is from 'dart:ui'.
Change to a subtype of 'Future<ImmutableBuffer>'.
  _i19.Future<dynamic> loadBuffer(String? key) => (super.noSuchMethod(
                       ^
../../Dev/flutter/packages/flutter/lib/src/services/asset_bundle.dart:64:30: Context: This is the overridden method ('loadBuffer').
  Future<ui.ImmutableBuffer> loadBuffer(String key) async {
```

**Comment by dkaera** [comment]
Hey @BetterB0y 
I added a Mockito package to the Floor sample project and mocked the PlatformAssetBundle. Is this what you are using in your project?

![image](https://user-images.githubusercontent.com/3041697/210323291-15510eed-06f0-4b2c-b4e6-1e5bf455f737.png)

As you can see, there is no error with `loadBuffer(String? key)`. Perhaps another interface has the same name which overrides the expected method mock.

**Comment by BetterB0y** [comment]
@dkaera I'm using AssetBundle from services

**Comment by BetterB0y** [comment]
Yeah. I did the same and it seems to work on example project. Weird... Any ideas what can it be?

**Comment by BetterB0y** [comment]
ImmutableBuffer is not creating its mock in any case. And I don't have import dart:ui. I commented every other mock class from generating and still nothing.

**Comment by BetterB0y** [comment]
Sorry for making problem... For future - deleting pubspec.lock helped :/

**Comment by dkaera** [comment]
no problem
nice to help :)
