### ISSUE TITLE
Like search from data base

### ISSUE THREAD

**Issue by praveenjaiswal16** [pinchbv/floor#728]
query to Like Search from the database 

my query is
@Query(
      'SELECT * FROM ParticipantsDetails where loggedInUserId = :loggedInUserId and LIKE firstName = :firstName ')

**Comment by dkaera** [comment]
@praveenjaiswal16 
your request is correct. Search patterns should be passed in the firstName argument, in your case. For instance if you want to search for names starting with `Jo`, the pattern would be - `Jo%`
See SQLite [tutorials] (https://www.sqlitetutorial.net/sqlite-like/) for more information.
Floor [doc](https://pinchbv.github.io/floor/daos/) with LIKE examples.

**Comment by dkaera** [comment]
no answer for a while
