### ISSUE TITLE
enum custom TypeConverters not working

### ISSUE THREAD

**Issue by zhangruiyu** [pinchbv/floor#735]
![image](https://user-images.githubusercontent.com/10591822/218968884-060d4f55-8d88-4f21-80d1-a6ddbad28d76.png)
![image](https://user-images.githubusercontent.com/10591822/218968922-097c1288-cd47-4f82-95e3-6c5357b24213.png)
![image](https://user-images.githubusercontent.com/10591822/218968966-0da323a5-e424-4d7e-aa26-376bc321a38e.png)
![image](https://user-images.githubusercontent.com/10591822/218969040-fd77cb77-8fe0-4c21-acf5-7f9c4bac9b84.png)
I have defined the Converter as documented, but it has no effect on the enumeration

**Comment by zhangruiyu** [comment]
![image](https://user-images.githubusercontent.com/10591822/218969609-0ac9794e-ec0d-4001-896e-8b87309cbba1.png)
I think that's the right answer, but that's not what's being generated so far

**Comment by dkaera** [comment]
@zhangruiyu good catch
TypeConverters has a lower priority than supported Dart types. Since `floor` supports Dart enumerations out of the box, you cannot override this. I think we can change this rule it in the next release.

**Comment by dkaera** [comment]
@zhangruiyu  
but anyway, floor supports Dart enums without TypeConverter and saves it in a correspond column with an int type. If it suits you fine you can skip declaring TypeConverter's for enums.

**Comment by zhangruiyu** [comment]
> @zhangruiyu  
> but in any case, `floor` supports Dart enumerations without `TypeConverter` and stores them in the appropriate column with int type. If that's fine with you, you don't have to declare `TypeConverter` for enumerations.

Normally this is fine, but dart now supports byname, which can be problematic if the enumeration changes with version updates (for example, adding a new enumeration between two)

**Comment by zhangruiyu** [comment]
As you said earlier, type converter should have a higher priority

**Comment by zhangruiyu** [comment]
![image](https://user-images.githubusercontent.com/10591822/222402210-1f942aeb-0546-44e0-8fb5-0329b91d56b4.png)
![image](https://user-images.githubusercontent.com/10591822/222402233-8f651a27-9bb1-48c2-88cd-2c086c4e8f48.png)
For example isar, which I think the floor should support

**Comment by dkaera** [comment]
Oh, that's a good one.
I was just thinking about how to implement backward compatibility support. 
Not sure about the second option `ordinal32`. The value of any column can be null if necessary. The number of enum declarations can be unlimited, at least I have not found any limit. What is the benefit of this approach?

**Comment by taosimple** [comment]
I have the same issue,  after upgrade code is broken, is there any work around.

**Comment by dkaera** [comment]
PR that changes `TypeConverters` priority is ready for review. #740 
Default `String` converters support will be later.

**Comment by zhangruiyu** [comment]
> PR that changes `TypeConverters` priority is ready for review. #740 
> Default `String` converters support will be later.

Great. When will the new version be released, thank you very much

**Comment by dkaera** [comment]
> > PR that changes `TypeConverters` priority is ready for review. #740
> > Default `String` converters support will be later.
> 
> Great. When will the new version be released, thank you very much

as soon as PINCH team approve it. I'm just a contributor 😁
