### ISSUE TITLE
An extra space between "From" and "Table" in Stream query is causing issue in streamcontroller and the widget is not getting updated

### ISSUE THREAD

**Issue by becjit** [pinchbv/floor#736]
It seems really weird.  I faced this in my project, so decided to try it with the official example. This is happening in both iphone and android emulators

Steps to reproduce:
1. Launch the official example from floor repo.
2. Add a task and save
3. a) Expected behaviour: Count and listview both getting updated
3. b) Actual behaviour: Same as above
4. insert an extra space between "From" and Table in following query and save. You dont even need to run the build
5.   @Query('SELECT DISTINCT COUNT(message) FROM task')
  Stream<int?> findUniqueMessagesCountAsStream();

6.  Add a task and save
7. a) Expected behaviour: Count and listview both getting updated
7.b) Actual behaviour: Listview is getting updated but not the count

Additional info: It's happening with other stream queries as well

Could someone confirm if they are seeing the same behaviour. 
I am feeling like I must be missing something

**Comment by becjit** [comment]
**Without space**
<img width="1269" alt="Screenshot 2023-02-15 at 9 30 03 PM" src="https://user-images.githubusercontent.com/2213422/219082452-16cae9f4-8d87-4936-927d-904585d25568.png">

**With space**
<img width="1369" alt="Screenshot 2023-02-15 at 9 30 37 PM" src="https://user-images.githubusercontent.com/2213422/219082484-4da31f38-fc2f-4a5f-89b2-6c8b1fdf0593.png">

**Comment by dkaera** [comment]
It's an interesting thing, and it certainly shouldn't be happening. 
Thanks for reporting the issue. I'll take a look what might be wrong.

**Comment by dkaera** [comment]
To be honest I wasn't able to replicate the issue. An extra space automatically removes in the generated code. Please take a look a sample code bellow.

![image](https://user-images.githubusercontent.com/3041697/222902382-9e7d9ec0-cae5-4f83-933d-4b3fd1b965ee.png)

**Comment by becjit** [comment]
Thnx @dkaera let me see if it get fixed after running the build. I remember running the build but will double check.

**Comment by becjit** [comment]
@dkaera running build fixes it it seems. You can close it
