### ISSUE TITLE
delete where in will not trigger steam

### ISSUE THREAD

**Issue by zhangruiyu** [pinchbv/floor#749]
delete where in will not trigger steam
![image](https://user-images.githubusercontent.com/10591822/227163182-4a47a8c4-5ade-4f58-92b8-05246564150e.png)

So logically should   call _changeListener? .add(_entityName);

**Comment by zhangruiyu** [comment]
![image](https://user-images.githubusercontent.com/10591822/227165766-15574227-f8b6-419a-8cd1-61a377a26ee5.png)
I think we should change @Delete

**Comment by dkaera** [comment]
yes, you're right. In the current version `Query` requests doesn't trigger the change notification.
But I have already implemented it in this PR #733
