### ISSUE TITLE
use Stream Invalid argument(s): Must not be null

### ISSUE THREAD

**Issue by akingyin1987** [pinchbv/floor#751]
When the exception was thrown, this was the stack: 
#0      ArgumentError.checkNotNull (dart:core/errors.dart:235:20)
#1      QueryAdapter.queryStream (package:floor/src/adapter/query_adapter.dart:64:42)
#2      _$PersonDao.findAllPersonCount (package:simple_flutter/db/AppDatabase.g.dart:152:26)
#3      _ButtonState.build (package:simple_flutter/widget/button_widget.dart:33:37)
#4      StatefulElement.build (package:flutter/src/widgets/framework.dart:5080:27)
#5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4968:15)
#6      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133:11)
#7      Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#8      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4950:5)
#9      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5124:11)
#10     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4944:5)
...     Normal element mounting (214 frames)
#224    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953:16)
#225    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6512:36)
#226    Element.updateChild (package:flutter/src/widgets/framework.dart:3682:18)
#227    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:6041:32)
#228    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6537:17)
#229    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#230    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#231    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133:11)
#232    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#233    StatefulElement.update (package:flutter/src/widgets/framework.dart:5156:5)
#234    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#235    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#236    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#237    ProxyElement.update (package:flutter/src/widgets/framework.dart:5301:5)
#238    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#239    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#240    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#241    ProxyElement.update (package:flutter/src/widgets/framework.dart:5301:5)
#242    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:107:11)
#243    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#244    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#245    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133:11)
#246    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#247    StatefulElement.update (package:flutter/src/widgets/framework.dart:5156:5)
#248    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#249    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#250    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#251    ProxyElement.update (package:flutter/src/widgets/framework.dart:5301:5)
#252    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:107:11)
#253    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#254    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#255    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133:11)
#256    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#257    StatefulElement.update (package:flutter/src/widgets/framework.dart:5156:5)
#258    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#259    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#260    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#261    ProxyElement.update (package:flutter/src/widgets/framework.dart:5301:5)
#262    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#263    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#264    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133:11)
#265    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#266    StatefulElement.update (package:flutter/src/widgets/framework.dart:5156:5)
#267    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#268    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6384:14)
#269    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#270    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6384:14)
#271    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#272    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#273    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#274    ProxyElement.update (package:flutter/src/widgets/framework.dart:5301:5)
#275    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#276    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#277    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133:11)
#278    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#279    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2743:19)
#280    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:863:21)
#281    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:381:5)
#282    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1289:15)
#283    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1218:9)
#284    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1076:5)
#285    _invoke (dart:ui/hooks.dart:145:13)
#286    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:338:5)
#287    _drawFrame (dart:ui/hooks.dart:112:31)
====================================================================================================

**Comment by dkaera** [comment]
Did you change the generated class?

**Comment by akingyin1987** [comment]
NO use  _queryAdapter.query() is not error ,but use _queryAdapter.queryStream() will happen error

**Comment by akingyin1987** [comment]
Why did not a changeListener be generated

**Comment by akingyin1987** [comment]
I found that the changeListener parameter was not used when creating a QueryAdapter
`class _$PersonDao extends PersonDao {
  _$PersonDao(
    this.database,
    this.changeListener,
  )   : _queryAdapter = QueryAdapter(database),`

**Comment by dkaera** [comment]
Since the QueryAdapter was designed to only fetch data from the database, it doesn't make sense to apply a `changeListener` for this adapter type. However, there is a pull request (#733 ) that parses the Query request and notifies the changeListener if it's a DELETE, UPDATE, or INSERT operation.
