### ISSUE TITLE
How can you set default current_timestamp

### ISSUE THREAD

**Issue by alexmro** [pinchbv/floor#753]
Is there a way to set a column's default value as `CURRENT_TIMESTAMP` or do I have to do it manually in the generated file?
Can you do it inside the callback function or using migrations?
Thanks

**Comment by dkaera** [comment]
Hey @alexmro  
It seems like you're looking to add a record timestamp to an existing table. To do this, you can follow these steps:

- Add an optional timestamp field to your entity model. You can set a default value in the model or set it in the migration callback using a SQLite query.
- Add a migration query that updates the table with the new timestamp column.
- Increase the database version to apply the migration.

To interact with the timestamp, you can try using this [option](https://www.sqlite.org/lang_datefunc.html) in SQLite. I haven't personally used this feature, but it looks promising.

I hope this helps! Let me know if you have any other questions.

**Comment by dkaera** [comment]
Looks like the issue has been sorted out and resolved. Closing the issue.
