### ISSUE TITLE
BUG(v1.4.2) - Unsupported query "SELECT * FROM abc WHERE key = :id" for List return type. It should be SELECT, since DELETE, UPDATE, INSERT returns `int` type.

### ISSUE THREAD

**Issue by royston-c** [pinchbv/floor#755]
Sorry I don't have an example but with the latest version v1.4.2 I see the new error:

Unsupported query "SELECT * FROM abc WHERE key = :id" for List return type. It should be SELECT, since DELETE, UPDATE, INSERT returns `int` type.

from https://github.com/pinchbv/floor/commit/f4650850999bc4a945316f924d762eac7c83bb7f 

I'm unsure why it is not parsed as a `SelectStatement` but the query is clearly a SELECT `SELECT * FROM abc WHERE key = :id`

**Comment by royston-c** [comment]
This is the actual code that generates the issue:

```
@Query('SELECT * FROM Profile WHERE key = :id')
Future<Profile?> getById(String id);
```

**Comment by dkaera** [comment]
> This is the actual code that generates the issue:
> 
> ```
> @Query('SELECT * FROM Profile WHERE key = :id')
> Future<Profile?> getById(String id);
> ```

hmm, I'm not sure if this method causes the error, because the error is related to the List return value type. Just checked the example project with 

```dart
@Query('SELECT * FROM task WHERE id = :id')
  Future<Task?> findTaskById(int id);
```

as a sample - it works fine. No errors are appearing when the method is invoked.

**Comment by dkaera** [comment]
@royston-c 
could you share the entire `Profile DAO` code?

**Comment by cpunion** [comment]
Same error.

```dart
import 'package:floor/floor.dart';
import 'package:spellingbee/models/plan.dart';

@dao
abstract class PlanDao {
  @Query("SELECT * FROM Plan ORDER BY id DESC")
  Future<List<Plan>> findAllPlans();

  @insert
  Future<int> insertPlan(Plan plan);

  @delete
  Future<void> deletePlan(Plan plan);
}
```
Errors:
```

```
Workaround: lock to floor 1.4.1

**Comment by dkaera** [comment]
The table name `plan` is a predefined token in SqlParser, which means that it cannot be used as a valid table name. This conflict results in incorrect parsing of query requests, causing the SqlParser to malfunction.

With table name `plan_table`, everything works fine.

**Comment by dkaera** [comment]
Looks like the issue has been sorted out and resolved. Closing the issue.

**Comment by sun-jiao** [comment]
same here. Changing `index` to `index_column` fixed it.

**Comment by theogrgs** [comment]
Same here. Changing `match` to `match_table` fixed it.
