### ISSUE TITLE
There are no entities added to the database annotation.

### ISSUE THREAD

**Issue by fatehiabdoalqadasi** [pinchbv/floor#757]
the build returns error

There are no entities added to the database annotation.
package:esouqqstore/database/appDatabase.dart:71:16
   ╷
71 │ abstract class AppDatabase extends FloorDatabase {
   │                ^^^^^^^^^^^

**Comment by fatehiabdoalqadasi** [comment]
@Database(version: 1, entities: [
  Account,
  AccountingClass,
  StoreCurrencyMapping,
  LocalizedProperty,
  User,
  InventoryTransaction,
  JournalVoucher,
  JournalVoucherEntry,
  JournalVoucherEntryDetail,
  BaseObject,
  StoreCustomer,
  StoreEmployee,
  StoreVendor,
  Store,
  Warehouse,
  Category,
  Product,
  ProductCategory,
  StoreProductMapping,
  Order,
])

**Comment by dkaera** [comment]
it's not clear
to create table for model you need to add `entity` annotation and also create a corespondent DAO abstract class. Please read the [doc](https://pinchbv.github.io/floor/).

**Comment by fatehiabdoalqadasi** [comment]
I have created entities and DAOs

**Comment by fatehiabdoalqadasi** [comment]
I was importing a file as

`import 'models/baseObjects/Warehouse.dart';`
when I change it to lowercase as

`import 'models/baseObjects/warehouse.dart';`
it works fine. The import was auto-generated
