### ISSUE TITLE
I Found a bug with query

### ISSUE THREAD

**Issue by xiaolei123** [pinchbv/floor#760]
myCode
```
@Query("SELECT * from Current")
Future<List<Current>> getCurrent();
```

log
```
Unhandled Exception: Bad state: Unsupported query "SELECT * from Current" for List return type.
 It should be SELECT, since DELETE, UPDATE, INSERT returns `int` type.
```

**Comment by dkaera** [comment]
Hello @xiaolei123
This problem occurs because `Current` key is a reserved word by `SqlParser`. Here is a similar discussion #755  List of reserved keys you can find [here](https://github.com/simolus3/drift/blob/4411e0c45922b95b58a57aa0126ec698e50c12b1/drift/lib/sqlite_keywords.dart#L40)

**Comment by dkaera** [comment]
It seems to have been answered.
