### ISSUE TITLE
MAX not working with int? in an empty database

### ISSUE THREAD

**Issue by Stensan** [pinchbv/floor#771]
When I call this MAX function and the database is empty, I get this error:

Exception has occurred.
_TypeError (type 'Null' is not a subtype of type 'int' in type cast)

```
@Query('SELECT MAX(position) FROM mytable')
Future<int?> getMaxPosition();
```

position is an int?

> int? position;

The database.g.dart looks like this:
```
@override
Future<int?> getMaxPosition() async {
    return _queryAdapter.query('SELECT MAX(position) FROM csinventoryitem',
        mapper: (Map<String, Object?> row) => row.values.first as int);
  }
```

Workaround is to check if the table is empty beforehand.

**Comment by dkaera** [comment]
Hey Stensan,
good catch, in this case the code is supposed to be next:
```dart
  @override
  Future<int?> getMaxPosition() async {
    return _queryAdapter.query<int?>('SELECT MAX(id) FROM csinventoryitem',
        mapper: (Map<String, Object?> row) => row.values.first as int?);
  }
```
if there are any concerns please let me know 😉

**Comment by Stensan** [comment]
Thanks, I will use rawQuery for this

**Comment by dkaera** [comment]
@Stensan ok, no problem
thank you for reporting the issue!

**Comment by ltxhhz** [comment]
@dkaera hello👋, I'm having this issue too, when will it be fixed
