### ISSUE TITLE
Error with floor_generator : There are no entities added to the database annotation.

### ISSUE THREAD

**Issue by gaelch** [pinchbv/floor#782]
Hello !

I created my entities, dao and the database following the documentation.
The entities are well annotated and are entered in the database annotation (@Database(version: 1, entities: [Account,]).

However, when I run the dart run build_runner build command, I get this error:

There are no entities added to the database annotation.
package:sirusmobile/database/SirusDatabase.dart:105:16
    ╷
105 │ abstract class SirusDatabase extends FloorDatabase {

I tried a bunch of things. 
Flutter clean / Flutter pub get, 
invalid and restart,
 change the imports, 
change the annotations, 
update the flutter and dart sdks, 
and even downgrade the floor and build_runner libraries.

Can anyone help me please?

Thank in advance !

**Comment by dkaera** [comment]
Hi @gaelch 
please share your ententy, dao and database classes. Did you add `@entity` annotation for your entity class?

**Comment by gaelch** [comment]
I should also add that the entities and the database are in the same package:

```dart
import 'package:sirusmobile/dao/AccessTokenDao.dart';

import 'package:sirusmobile/database/SirusDatabase.dart';
```
Dart SDK version: 3.1.2 
Flutter 3.13.5 
floor: ^1.4.2
floor_generator: ^1.4.2
build_runner: ^2.1.2

**Comment by gaelch** [comment]
Thank you for your reply.

- Indeed the crash points to line 105 │ abstract class SirusDatabase extends FloorDatabase {

-Regarding the second issue you raise, I couldn't identify any change because I first created all the entities and then attempted to generate the database.g.dart file.

It doesn't seem to me that there are any typos in the entity class names.
I'm checking that.

Again thanks to you.

**Comment by gaelch** [comment]
I can add that the g.dart files for the entities are all created.

**Comment by dkaera** [comment]
> I can add that the g.dart files for the entities are all created.

Hmm, I don't think that's necessarily the case. The reason could be reusing models that already use JsonSerialisable. So probably to check you can create a sample `Database` with only one `entity` + `DAO` for this model. For instance `AccesToken`. Entity class shouldn't be marked as `JsonSerialisable`. If it works, try to add functionality step by step to figure out what the thing especially breaks the generation.

**Comment by gaelch** [comment]
I just tried this.
Keep only AccesToken
Remove @JsonSerializable in this class. 
Remove all dao except AccessTokenDao and remove Converters.
I then did the same thing again with the Chauffeur class.
Unfortunately I still have the same error.

**Comment by gaelch** [comment]
Is it better to separate the entity classes (for database) and model classes (for http) ?

**Comment by gaelch** [comment]
I solved the problem. I did two things for this.

In the DAOs the names of the classes in the queries were not correct ones.

In the entities I did not have the fromMap and toMap methods but only the json methods fromJson and toJson.

Hope this can help some people.

Thanks you Dmytro Puzak

Good day !

**Comment by gaelch** [comment]
I solved the problem. I did two things for this.

In the DAOs the names of the classes in the queries were not correct ones.

In the entities I did not have the fromMap and toMap methods but only the json methods fromJson and toJson.

Hope this can help some people.

Thanks you Dmytro Puzak

Good day !
