### ISSUE TITLE
dependecy conflict with riverpod_lint 2.3.3

### ISSUE THREAD

**Issue by PawnBreak2** [pinchbv/floor#796]
Looks like floor_generator is not working anymore with the latest version of riverpod linter since floor_generator has not migrated yet to analyzer 6.0, here's the message:

Because floor_generator >=1.4.0 depends on analyzer ^5.0.0 and riverpod_lint >=2.2.1 depends on analyzer ^6.0.0, floor_generator >=1.4.0 is incompatible with riverpod_lint >=2.2.1.
So, because ****** depends on both riverpod_lint ^2.3.3 and floor_generator ^1.4.2, version solving failed.

Seems like a blocking issue (and maybe easily fixed), since riverpod_lint is widely used.
Thanks!

**Comment by kinglighthill** [comment]
Any solution for this? I'm currently facing this issue.

**Comment by dkaera** [comment]
The fix is already in the development branch, the release of the new version should be very soon
