### ISSUE TITLE
dependencies issue

### ISSUE THREAD

**Issue by GeorgeNady** [pinchbv/floor#817]
floor_generator 1.4.2 depends on analyzer ^5.0.0
and many updated dependencies depends on analyzer ^6.4.1

----
### so kindly update analyzer version to be ^6.4.1

**Comment by dkaera** [comment]
analyzer has already been updated, but not yet released

**Comment by jillellamudisurya** [comment]
@dkaera When will the release be published?

**Comment by dkaera** [comment]
@stephanmantel Let's push a new release. The current dev version has accumulated some significant changes.

**Comment by stephanmantel** [comment]
Indeed, I want to make a release soon

**Comment by stephanmantel** [comment]
New version has been released
